version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bg-eraser-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bg-eraser-frontend
    ports:
      - "5000:80"
    environment:
      - API_HOST=${API_HOST:-http://backend:3001}
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
